<?php

namespace Database\Seeders;

use App\Models\LegalPage;
use Illuminate\Database\Seeder;

/**
 * Seeds the 3 legal pages a donation-collecting NGO taking online payments
 * needs: Privacy Policy, Terms & Conditions, and Refund & Cancellation
 * Policy (this last one specifically because Razorpay requires a visible
 * refund/cancellation policy on the merchant's site before activating live
 * payments). None of this content existed on the original static site, so
 * it's freshly drafted here in reasonable, standard NGO-appropriate form —
 * same "drafted, not migrated" convention as ImpactPageSeeder/GalleryPageSeeder.
 *
 * IMPORTANT: this is a solid starting template, not legal advice. It should
 * be reviewed by the client/their counsel before the site goes live with
 * real donations — same caveat that applies to any legal boilerplate.
 * Content is fully admin-editable afterwards via Legal Pages in the admin
 * panel (see LegalPageResource), so revisions don't need a developer.
 */
class LegalPagesSeeder extends Seeder
{
    public function run(): void
    {
        LegalPage::updateOrCreate(
            ['slug' => 'privacy-policy'],
            [
                'title' => 'Privacy Policy',
                'order' => 1,
                'is_published' => true,
                'body' => <<<HTML
<p>Ichhe Puran ("we", "us", "our", operating as Ichhe Puran Trust) respects your privacy and is committed to protecting the personal information you share with us through this website.</p>

<h2>Information We Collect</h2>
<p>We collect information you provide directly, such as your name, email address, phone number, and postal address, when you make a donation, apply to volunteer, submit a CSR partnership inquiry, subscribe to our newsletter, or contact us through the website.</p>

<h2>How We Use Your Information</h2>
<ul>
<li>To process and acknowledge donations</li>
<li>To respond to volunteer applications and CSR inquiries</li>
<li>To send newsletter updates, if you have subscribed</li>
<li>To respond to messages sent through our contact form</li>
<li>To comply with legal and regulatory record-keeping requirements for a registered trust</li>
</ul>
<p>We do not sell, rent, or trade your personal information to third parties for marketing purposes.</p>

<h2>Payment Information</h2>
<p>Online donations are processed through Razorpay, a licensed payment gateway. We do not store your card, UPI, or net-banking credentials on our servers — these are collected and processed directly by Razorpay in accordance with their own privacy and security policies. We retain only the donation amount, donor-provided contact details, and the payment reference generated by Razorpay.</p>

<h2>Data Sharing</h2>
<p>We may share information with trusted service providers who help us operate this website and process donations (such as Razorpay, our hosting provider, and email service providers), solely to the extent necessary to provide those services, and with government or regulatory authorities where required by law.</p>

<h2>Data Security</h2>
<p>We take reasonable technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.</p>

<h2>Your Rights</h2>
<p>You may request access to, correction of, or deletion of your personal information held by us at any time by writing to us using the contact details below. You may unsubscribe from our newsletter at any time via the link in any newsletter email.</p>

<h2>Children's Privacy</h2>
<p>This website is not directed at children under 18, and we do not knowingly collect personal information from children.</p>

<h2>Changes to This Policy</h2>
<p>We may update this Privacy Policy from time to time. The date of the most recent update is shown at the top of this page.</p>

<h2>Contact Us</h2>
<p>For any privacy-related questions or requests, please contact us at info@ichhepuran.org or write to us at 12/A Green Avenue, Salt Lake City, Sector 5, Kolkata, West Bengal - 700091.</p>
HTML,
            ]
        );

        LegalPage::updateOrCreate(
            ['slug' => 'terms-and-conditions'],
            [
                'title' => 'Terms & Conditions',
                'order' => 2,
                'is_published' => true,
                'body' => <<<HTML
<p>These Terms & Conditions govern your use of the Ichhe Puran website (the "Site"), operated by Ichhe Puran Trust. By using this Site, you agree to these terms.</p>

<h2>Use of This Website</h2>
<p>You agree to use this Site only for lawful purposes and in a way that does not infringe the rights of, or restrict or inhibit the use and enjoyment of, this Site by any third party.</p>

<h2>Donations</h2>
<p>All donations made through this Site are voluntary contributions to Ichhe Puran Trust in support of its charitable activities. Donations are processed securely through Razorpay. Please see our <a href="/refund-and-cancellation-policy">Refund &amp; Cancellation Policy</a> for information on refunds.</p>

<h2>Volunteering &amp; CSR Partnerships</h2>
<p>Submitting a volunteer application or CSR partnership inquiry through this Site does not, by itself, create any binding commitment on either party. We will contact you to discuss next steps following a review of your submission.</p>

<h2>Intellectual Property</h2>
<p>All content on this Site — including text, images, logos, and design — is the property of Ichhe Puran Trust unless otherwise credited, and may not be reproduced or used without our prior written permission.</p>

<h2>Third-Party Links</h2>
<p>This Site may contain links to third-party websites. We are not responsible for the content, accuracy, or privacy practices of any linked external site.</p>

<h2>Limitation of Liability</h2>
<p>While we make every effort to keep information on this Site accurate and up to date, Ichhe Puran Trust makes no warranties about the completeness or accuracy of the content and shall not be liable for any loss or damage arising from the use of this Site.</p>

<h2>Governing Law</h2>
<p>These terms are governed by the laws of India, and any disputes shall be subject to the jurisdiction of the courts in Kolkata, West Bengal.</p>

<h2>Changes to These Terms</h2>
<p>We may revise these Terms & Conditions at any time. Continued use of the Site after changes are posted constitutes acceptance of the revised terms.</p>

<h2>Contact Us</h2>
<p>Questions about these terms can be sent to info@ichhepuran.org.</p>
HTML,
            ]
        );

        LegalPage::updateOrCreate(
            ['slug' => 'refund-and-cancellation-policy'],
            [
                'title' => 'Refund & Cancellation Policy',
                'order' => 3,
                'is_published' => true,
                'body' => <<<HTML
<p>This policy explains how Ichhe Puran Trust handles refunds and cancellations for donations made through this website.</p>

<h2>Donations Are Generally Non-Refundable</h2>
<p>Donations made to Ichhe Puran Trust are voluntary contributions toward our charitable programs and are, as a general rule, non-refundable once processed, as funds are often allocated to ongoing project work soon after receipt.</p>

<h2>Exceptions</h2>
<p>We will review and process a refund in the following circumstances:</p>
<ul>
<li>A technical or payment gateway error resulted in a duplicate charge for the same donation</li>
<li>An incorrect amount was charged due to a verified error on our end</li>
<li>Funds were debited from your account but the donation was not successfully recorded on our system (a failed transaction)</li>
</ul>

<h2>How to Request a Refund</h2>
<p>If you believe your donation qualifies for a refund under the exceptions above, please contact us at info@ichhepuran.org within 7 days of the transaction, including your name, the donation amount, the date of the transaction, and (if available) the payment reference or order ID from your confirmation.</p>

<h2>Processing Time</h2>
<p>Approved refunds are processed back to the original payment method via Razorpay and typically reflect within 5–10 business days, depending on your bank or payment provider.</p>

<h2>Failed or Incomplete Transactions</h2>
<p>If a payment is debited from your account but you do not receive a donation confirmation, please do not attempt the payment again immediately — contact us first so we can verify the transaction status before you retry.</p>

<h2>Contact Us</h2>
<p>For any refund or cancellation queries, reach us at info@ichhepuran.org or call the number listed on our <a href="/contact">Contact page</a>.</p>
HTML,
            ]
        );
    }
}
